apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: pravega
  labels:
    app.kubernetes.io/name: "pravega-cluster"
spec:
  version: 0.7.0
  zookeeperUri: pravega-zk-client:2181
  externalAccess:
    enabled: false
    type: LoadBalancer
  bookkeeperUri: pravega-bk-bookie-headless:3181
  pravega:
    image:
      repository: pravega/pravega
    controllerReplicas: 1
    controllerResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"
    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"
    debugLogging: false
    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 20Gi
    longtermStorage:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
    options:
      bookkeeper.bkEnsembleSize:   "3"
      bookkeeper.bkWriteQuorumSize:   "3"
      bookkeeper.bkAckQuorumSize:   "3"
      bookkeeper.bkWriteTimeoutMillis:   "60000"
      bookkeeper.maxOutstandingBytes:   "33554432"
      pravegaservice.cacheMaxSize:   '3221225472   '
      pravegaservice.cacheMaxTimeSeconds:   "600"
      writer.flushThresholdBytes:   "67108864"
      writer.flushThresholdMillis:   "2000"
      writer.maxFlushSizeBytes:   "67108864"
      writer.minReadTimeoutMillis:   "200"
      hdfs.blockSize:   "67108864"
      pravegaservice.containerCount:   "32"
      controller.containerCount:   "32"
      pravegaservice.threadPoolSize:   "30"
      controller.retention.bucketCount:   "10"
      controller.service.asyncTaskPoolSize:   "20"
      controller.retention.threadCount:   "4"
      log.level:   INFO
      metrics.dynamicCacheSize:   "100000"
      metrics.enableStatistics:   "true"
      metrics.enableStatsDReporter:   "false"
      metrics.statsdHost:   telegraph.default
      metrics.statsdPort:   "8125"
      metrics.enableInfluxDBReporter:   "true"
      metrics.outputFrequencySeconds:   "10"
      metrics.influxDBURI:   http://172.28.60.13:8086
      controller.metrics.dynamicCacheSize:   "100000"
      controller.metrics.enableStatistics:   "true"
      controller.metrics.enableStatsDReporter:   "false"
      controller.metrics.statsdHost:   telegraph.default
      controller.metrics.statsdPort:   "8125"
      controller.metrics.enableInfluxDBReporter:   "true"
      controller.metrics.outputFrequencySeconds:   "10"
      controller.metrics.influxDBURI:   http://172.28.60.13:8086
      controller.transaction.maxLeaseValue:  "86400000"
    segmentStoreJVMOptions:
    - -Xmx4g
    - -XX:MaxDirectMemorySize=4g
