apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: {{ template "pravega.fullname" . }}
spec:
  version: {{ .Values.version }}
  zookeeperUri: {{ .Values.zookeeperUri }}
  externalAccessEnabled: {{ .Values.externalAccessEnabled }}
  bookkeeper:
    {{- if .Values.externalAccessEnabled }}
    serviceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
    image:
      repository: {{ .Values.bookkeeper.image.repository }}
    replicas: {{ .Values.bookkeeper.replicas }}
    resources:
      requests:
        memory: "3Gi"
        cpu: "1000m"
      limits:
        memory: "5Gi"
        cpu: "2000m"
    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: {{ .Values.bookkeeper.storage.ledgerVolumeRequest }}
      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: {{ .Values.bookkeeper.storage.journalVolumeRequest }}
      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: {{ .Values.bookkeeper.storage.indexVolumeRequest }}
    autoRecovery: {{ .Values.bookkeeper.autoRecovery }}
  pravega:
    image:
      repository: {{ .Values.pravega.image.repository }}
    controller:
      {{- if .Values.externalAccessEnabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      replicas: {{ .Values.pravega.controller.replicas }}
      debugLogging: {{ .Values.pravega.controller.debugLogging }}
      externalAccess:
        type: {{ .Values.pravega.controller.externalAccess.type }}
      resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "2000m"
    segmentstore:
      {{- if .Values.externalAccessEnabled }}
      serviceAccountName: {{ .Values.serviceAccount.name  }}
      {{- end }}
      replicas: {{ .Values.pravega.segmentstore.replicas }}
      debugLogging: {{ .Values.pravega.segmentstore.debugLogging }}
      externalAccess:
        type: {{ .Values.pravega.segmentstore.externalAccess.type }}
      resources:
        requests:
          memory: "3Gi"
          cpu: "1000m"
        limits:
          memory: "5Gi"
          cpu: "2000m"
      cacheVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: {{ .Values.pravega.segmentstore.cacheVolumeRequest }}
    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: {{ .Values.pravega.tier2 }}
