apiVersion: apps/v1
kind: Deployment
metadata:
  name: pravega-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pravega-operator
  template:
    metadata:
      labels:
        name: pravega-operator
        component: pravega-operator
    spec:
      serviceAccountName: pravega-operator
      containers:
        - name: pravega-operator
          image: pravega/pravega-operator:0.4.4
          ports:
          - containerPort: 60000
            name: metrics
          volumeMounts:
          - name: webhook-cert
            mountPath: "/tmp/k8s-webhook-server/serving-certs"
            readOnly: true
          - name: versions-volume
            mountPath: "/tmp/config"             
          command:
          - pravega-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: pravega-operator
      volumes:
      - name: webhook-cert
        secret:
          secretName: selfsigned-cert-tls
      - name: versions-volume
        configMap:
          name: supported-upgrade-paths