{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pravega-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pravega-operator.commonLabels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ template "pravega-operator.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
