# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 0.5.0
zookeeperUri: zk-client:2181
externalAccessEnabled: false
serviceAccount:
  name: pravega-components

bookkeeper:
  image:
    repository: pravega/bookkeeper
  replicas: 3
  storage:
    ledgerVolumeRequest: 10Gi
    journalVolumeRequest: 10Gi
    indexVolumeRequest: 10Gi
  autoRecovery: true

pravega:
  image:
    repository: pravega/pravega
  controller:
    replicas: 1
    debugLogging: false
    externalAccess:
      type: LoadBalancer
  segmentstore:
    replicas: 1
    debugLogging: false
    externalAccess:
      type: LoadBalancer
    cacheVolumeRequest: 20Gi
  tier2: pravega-tier2
