## Default values for pravega.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

version: 0.7.0

tls: {}
  # secret:
  #   controller: "controller-pki"
  #   segmentStore: "segmentstore-pki"
  # caBundle: ""

authentication:
  enabled: false
  ## passwordAuthSecret is ignored if authentication is disabled
  passwordAuthSecret:

zookeeperUri: zookeeper-client:2181
bookkeeperUri: bookkeeper-bookie-headless:3181

externalAccess:
  enabled: false
  ## type and domainName are ignored if external access is disabled
  type: LoadBalancer
  domainName:

image:
  repository: pravega/pravega
  pullPolicy: IfNotPresent

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
  backoffLimit: 10

debugLogging: false

serviceAccount:
  name: pravega-components

controller:
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 3Gi
  ## service type and annotations are ignored if external access is disabled
  service:
    ## used to override the service type for controller
    type:
    annotations: {}
  jvmOptions: []

segmentStore:
  replicas: 1
  secret: {}
    # name:
    # path:
  env:
  resources:
    requests:
      cpu: 1000m
      memory: 3Gi
    limits:
      cpu: 2000m
      memory: 5Gi
  ## service type and annotations are ignored if external access is disabled
  service:
    ## used to override the service type for segmentStore
    type:
    annotations: {}
  jvmOptions: []

storage:

  longtermStorage:
    ## configure the long term storage backend type
    ## accepted values : filesystem/ecs/hdfs
    ## default option is filesystem
    type: filesystem

    ## fileSystem is used to configure a pre-created Persistent Volume Claim
    ## as the long term storage backend
    ## this is the default longtermStorage type
    filesystem:
      pvc: pravega-tier2

    ## ecs is used to configure a Dell EMC ECS system as the long term storage backend
    ## considered only if storage.longtermStorage.type = ecs
    ecs: {}
      # configUri: ""
      # bucket: ""
      # prefix: ""
      # credentials: ""

    ## hdfs is used to configure an HDFS system as long term storage backend
    ## considered only if storage.longtermStorage.type = hdfs
    hdfs: {}
      # uri: ""
      # root: ""
      # replicationFactor:

  cache:
    size: 20Gi
    className: standard

options:
  # bookkeeper.ack.quorum.size: "3"
