# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 0.7.0

tls: {}
  # secret:
  #   controller: "controller-pki"
  #   segmentStore: "segmentstore-pki"
  # caBundle: ""

authentication:
  enabled: false
  passwordAuthSecret:

zookeeperUri: zk-client:2181
bookkeeperUri: pravega-bk-bookie-headless:3181

externalAccess:
  enabled: false
  type: LoadBalancer
  domainName:

image:
  repository: pravega/pravega
  pullPolicy: IfNotPresent

debugLogging: false

serviceAccount:
  name: pravega-components

controller:
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 3Gi
  service:
    type:
    annotations: {}
  jvmOptions: []

segmentStore:
  replicas: 1
  secret: {}
    # name:
    # path:
  env:
  resources:
    requests:
      cpu: 1000m
      memory: 3Gi
    limits:
      cpu: 2000m
      memory: 5Gi
  service:
    type:
    annotations: {}
  jvmOptions: []

storage:
  longtermStorage:
    # configure any one of filesystem/ecs/hdfs as the long term storage backend
    # default option is filesystem
    type: filesystem
    # FileSystem is used to configure a pre-created Persistent Volume Claim
    # as the long term storage backend
    filesystem:
      pvc: pravega-tier2
    # ecs is used to configure a Dell EMC ECS system as the long term storage backend
    ecs: {}
      # configUri: ""
      # bucket: ""
      # prefix: ""
      # credentials: ""
    # Hdfs is used to configure an HDFS system as long term storage backend
    hdfs: {}
      # uri: ""
      # root: ""
      # replicationFactor:
  cache:
    size: 20Gi
    className: standard

# add pravega options in the following format
options:
  enabled: false
  # provide the list of key-value pairs for pravega options
  list:
  # - key: ""
  #   value: ""
