kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pravega-tier2
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  zookeeperUri: zk-client:2181
  externalAccessEnabled: true

  bookkeeper:
    image:
      repository: pravega/bookkeeper
      tag: latest
      pullPolicy: IfNotPresent

    replicas: 3

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

    autoRecovery: true

  pravega:
    image:
      repository: pravega/pravega
      tag: latest
      pullPolicy: IfNotPresent

    controller:
      replicas: 1
      externalAccess:
        type: LoadBalancer

    segmentstore:
      replicas: 3
      externalAccess:
        type: LoadBalancer
        
      cacheVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 20Gi

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
