# Default values for pravega-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#prabhu75/pravega_operator:makedep_1
image:
  repository: prabhu75/pravega_operator
  tag: makedep_1
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings
rbac:
  create: true

## Service account names and whether to create them
serviceAccount:
  create: true
  name: pravega-operator

# Whether to create custom resource
crd:
  create: true
