## Default values for pravega-operator.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

image:
  repository: pravega/pravega-operator
  tag: latest
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings.
rbac:
  create: true

## Service account names and whether to create it.
serviceAccount:
  create: true
  name: pravega-operator

## Whether to create the CRD.
crd:
  create: true

  ## Whether to enable test mode.
  testmode: false

webhookCert:
  ## Whether to use a new self-signed certificate.
  selfsigned: true
  ## If false, the following needs to be provided, and must match the CRD webhook CA:
  #crt: <cert_crt>
  #key: <cert_key>

## Specifies which namespace the Operator should watch over.
## An empty string means all namespaces.
watchNamespace: ""
