# Default values for pravega-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: srishtithakkar/pravega-operator
  tag: 0.4.3-version-support
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings
rbac:
  create: true

## Service account names and whether to create them
serviceAccount:
  create: true
  name: pravega-operator

# Whether to create custom resource
crd:
  create: true
