
# workflow name
name: CI

# on events
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
# jobs to run
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.8
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.8
      id: go
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
    - name: Get output
      run: echo ${{ steps.date.outputs.date }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Gofmt and License checks
      run: make check
    - name: unit tests
      run: make test-unit
    - name: Codecov
      uses: codecov/codecov-action@v1.0.12
