
# workflow name
name: CI

# on events
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  KUBECTL_VERSION: v1.15.0
  OPERATOR_SDK_VERSION: v0.17.0
# jobs to run
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.8
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.8
      id: go
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
    - name: Get output
      run: echo ${{ steps.date.outputs.date }}
    - name: Set env
      run: echo ::set-env name=CLUSTER_NAME::pravega-operator-travis-${{ steps.date.outputs.date }}
    - name: Test
      run: echo $CLUSTER_NAME
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Gofmt and License checks
      run: make check
    - name: unit tests
      run: make test-unit
    - name: Codecov
      uses: codecov/codecov-action@v1.0.12
    - run: curl -Lo packet-cli  https://github.com/packethost/packet-cli/releases/download/0.0.7/packet-linux-amd64 && chmod +x packet-cli && sudo mv packet-cli /usr/local/bin/
    - run: ssh-keygen -f ~/.ssh/id_rsa -P ""
    - run: pub_key=`cat ~/.ssh/id_rsa.pub`
    - run: echo " publc key is $pub_key"
